name: CI

on: [push]

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: macos-latest
    name: Test Suite
    if: ${{ !contains(github.event.head_commit.message, '#skipci') }}
    steps:
      - uses: actions/checkout@v3
      - uses: fwal/setup-swift@ffb5a44dd03d3d22fb26f48fa43e43fa4ce655a7
        with:
          swift-version: "5.7"
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
